export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const TOGGLE_TODO_ITEM = "TOGGLE_TODO_ITEM";
export const SELECT_ALL = "SELECT_ALL";
export const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";
export const ON_SUBMIT_EDITING_INPUT = "ON_SUBMIT_EDITING_INPUT";
export const UPDATE_VIEW = "UPDATE_VIEW";
